
// The current Java solution for the `hasDuplicate` problem uses a nested loop to compare every pair of elements. generated by Claude Fable 5 

public boolean hasDuplicate(int[] nums) {
    for (int i = 0; i < nums.length; i++) {
        for (int j = i + 1; j < nums.length; j++) {
            if (nums[i] == nums[j]) {
                return true;
            }
        }
    }
    return false;
}
