
// The current Java solution for the `hasDuplicate` problem uses a nested loop to compare every pair of elements. generated by Claude Fable 5 

public boolean hasDuplicate(int[] nums) {
    HashSet<Integer> seen = new HashSet<>();

    for (int num : nums) {
        if (!seen.add(num)) {
            return true;
        }
    }

    return false;
}
